[package]
name = "program-escrow"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
<<<<<<< HEAD
soroban-sdk = "22.0.0"
grainlify-interfaces = { path = "../interfaces" }

[dev-dependencies]
soroban-sdk = { version = "22.0.0", features = ["testutils"] }
=======
soroban-sdk = "22.0.8"

[dev-dependencies]
soroban-sdk = { version = "22.0.8", features = ["testutils"] }
>>>>>>> master

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
